name: Terraform Destroy
on:
  workflow_dispatch:
  schedule:
    - cron:  '00 18 * * 5'    
jobs:
  build:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare environment variables
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: | 
          # Parse Azure secret into Terraform variables
          echo "ARM_CLIENT_ID=$( jq -r '.clientId' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV;
          echo "ARM_CLIENT_SECRET=$( jq -r '.clientSecret' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV;
          echo "ARM_SUBSCRIPTION_ID=$( jq -r '.subscriptionId' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV;
          echo "ARM_TENANT_ID=$( jq -r '.tenantId' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV
        shell: bash          

      - name: Terraform Init 
        id: init 
        run: |
          terraform -chdir=demo init \
            -backend-config="subscription_id=${{ vars.TFSTATE_SUBSCRIPTION_ID }}" \
            -backend-config="resource_group_name=${{ vars.TFSTATE_RESOURCE_GROUP }}" \
            -backend-config="storage_account_name=${{ vars.TFSTATE_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ vars.TFSTATE_CONTAINER }}" \
            -backend-config="key=${{ vars.TFSTATE_KEY }}" \
            -backend-config="use_azuread_auth=true"

      - name: Terraform Destroy 
        id: destroy
        env: 
          TF_VAR_subscription_id: ${{ env.ARM_SUBSCRIPTION_ID }}
        run: terraform -chdir=demo destroy -auto-approve -no-color
        