name: PR Validation

on: [push, pull_request]

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }} 
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 

jobs:
  build:
    name: Terrraform Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt --recursive -check

      - name: 'Az CLI login'
        uses: azure/login@v1

      - name: Terraform Init
        id: init
        run: terraform -chdir=tests init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=tests validate -no-color

      - name: Terraform Test
        id: test
        run: terraform -chdir=tests test -no-color
