name: Terraform Validation
on: [push, pull_request]
jobs:
  build:
    name: Terrraform Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt --recursive -check

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        id: init
        run: terraform -chdir=tests/setup init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=tests/setup validate -no-color

      - name: Terraform Test
        id: test
        run: terraform test -no-color
