name: Terraform Validation
on:
  - pull_request
jobs:
  build:
    name: Validation & Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Terraform Format
        id: fmt
        run: terraform fmt --recursive -check

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        id: init
        run: terraform -chdir=tests init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=tests validate -no-color

      - name: Terraform Test
        id: test
        run: terraform -chdir=tests test -no-color
